import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import '@xyflow/react/dist/style.css';
import { CommandPalette } from '@/components/search/command-palette';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${GeistSans.className} antialiased`}
      >
        {children}
        {/* <CommandPalette /> */}
      </body>
    </html>
  );
}
